package stock.exchange.integration;

/**
 * The interface represents any possible type of consumers for the events
 * generated by the stock market runners.
 */
public interface Downstream<T> {

  /**
   * The method is being invoked by market runners.
   * 
   * The implementation should be non-blocking
   * 
   * @param t the event object
   */
  void accept(T t);

}
