package stock.exchange.integration;

/**
 * The interface represents potential consumers for events generated by the
 * stock market runners.
 */
public interface Downstream<T> {

  /**
   * This method is invoked by market runners.
   * 
   * The implementation should be non-blocking.
   **
   * @param t the event object
   */
  void accept(T t);

}
