package stock.exchange.integration;

/**
 * 
 * The interface represents consumers for the events of rejection, failure, or
 * unprocessed events generated by the stock market runners. The closest
 * implementation analogy is a dead-letter queue.
 */
public interface NonblockingNonFailingJunkDownstream<T> {

  /**
   * The method is being invoked by market runners
   * 
   * There are two important considerations for the implementations of this
   * interface:
   * 
   * The implementation should be non-blocking
   * 
   * The implementation should not throw exceptions or errors
   * 
   * @param t the event object
   * @param e the exception that caused the event to be sent to rejection
   */

  void accept(T t, Throwable e);

}
